/**
 * server.js — NutriGuide AI Express Server
 *
 * Responsibilities:
 *   - Serves the static frontend from /public
 *   - Manages IBM watsonx.ai IAM token exchange (cached 55 min)
 *   - Provides the callGranite() wrapper used by all agents
 *   - Mounts all API routes and delegates to agents.js
 */

'use strict';

require('dotenv').config();
const express = require('express');
const axios   = require('axios');
const path    = require('path');

const {
  nutritionKnowledgeAgent,
  dietRecommendationAgent,
  foodRecommendationAgent,
  healthAdvisoryAgent,
  foodLogFeedbackAgent
} = require('./agents');

const { lookupFood } = require('./rag');

// ---------------------------------------------------------------------------
// Configuration
// ---------------------------------------------------------------------------

const PORT            = process.env.PORT            || 3000;
const WATSONX_API_KEY = process.env.WATSONX_API_KEY;
const PROJECT_ID      = process.env.WATSONX_PROJECT_ID;
const REGION          = process.env.WATSONX_REGION  || 'us-south';

const GRANITE_MODEL   = process.env.WATSONX_MODEL_ID || 'ibm/granite-4-h-small';
const WATSONX_URL     = `https://${REGION}.ml.cloud.ibm.com/ml/v1/text/generation?version=2023-05-29`;
const IAM_TOKEN_URL   = 'https://iam.cloud.ibm.com/identity/token';

// ---------------------------------------------------------------------------
// IAM Token Cache
// ---------------------------------------------------------------------------

let iamTokenCache = null;   // { token: string, expiresAt: number }

/**
 * Returns a valid IBM IAM Bearer token.
 * Exchanges the API key for a new token when the cached one is about to expire.
 */
async function getIAMToken() {
  const now = Date.now();

  if (iamTokenCache && now < iamTokenCache.expiresAt) {
    return iamTokenCache.token;
  }

  const response = await axios.post(
    IAM_TOKEN_URL,
    new URLSearchParams({
      grant_type: 'urn:ibm:params:oauth:grant-type:apikey',
      apikey: WATSONX_API_KEY
    }),
    { headers: { 'Content-Type': 'application/x-www-form-urlencoded' } }
  );

  const token     = response.data.access_token;
  const expiresIn = response.data.expires_in || 3600; // seconds

  // Cache for 55 minutes (slightly less than actual expiry for safety)
  iamTokenCache = {
    token,
    expiresAt: now + Math.min(expiresIn - 300, 3300) * 1000
  };

  return token;
}

// ---------------------------------------------------------------------------
// Granite Wrapper
// ---------------------------------------------------------------------------

/**
 * callGranite(prompt)
 *
 * Sends a prompt to IBM Granite via watsonx.ai and returns the generated text.
 * This function is passed into every agent so they never touch credentials directly.
 *
 * @param {string} prompt
 * @returns {Promise<string>}
 */
async function callGranite(prompt) {
  const token = await getIAMToken();

  const payload = {
    model_id:   GRANITE_MODEL,
    project_id: PROJECT_ID,
    input:      prompt,
    parameters: {
      max_new_tokens: 700,
      temperature:    0.7,
      top_p:          0.9,
      repetition_penalty: 1.1
    }
  };

  const response = await axios.post(WATSONX_URL, payload, {
    headers: {
      Authorization:  `Bearer ${token}`,
      'Content-Type': 'application/json',
      Accept:         'application/json'
    }
  });

  // Extract generated text from watsonx.ai response structure
  const results = response.data?.results;
  if (results && results.length > 0) {
    return results[0].generated_text.trim();
  }

  throw new Error('No text generated by Granite.');
}

// ---------------------------------------------------------------------------
// Express App
// ---------------------------------------------------------------------------

const app = express();
app.use(express.json());
app.use(express.static(path.join(__dirname, 'public')));

// ---------------------------------------------------------------------------
// Helper — validate & parse profile from request body
// ---------------------------------------------------------------------------

function parseProfile(body) {
  const { age, weight, goal, diet } = body.profile || {};
  return {
    age:    age    || 25,
    weight: weight || 70,
    goal:   goal   || 'maintain weight',
    diet:   diet   || 'non-veg'
  };
}

// ---------------------------------------------------------------------------
// Helper — uniform error response
// ---------------------------------------------------------------------------

function handleError(res, error) {
  console.error('[NutriGuide Error]', error?.response?.data || error.message);
  const msg =
    error?.response?.data?.errors?.[0]?.message ||
    error?.response?.data?.message ||
    error.message ||
    'An error occurred. Please try again.';
  res.status(500).json({ error: msg });
}

// ---------------------------------------------------------------------------
// Route 1 — POST /api/chat  (Nutrition Knowledge Agent)
// ---------------------------------------------------------------------------

app.post('/api/chat', async (req, res) => {
  try {
    const { message } = req.body;
    if (!message || !message.trim()) {
      return res.status(400).json({ error: 'Message is required.' });
    }
    const profile  = parseProfile(req.body);
    const response = await nutritionKnowledgeAgent(callGranite, message.trim(), profile);
    res.json({ response });
  } catch (err) {
    handleError(res, err);
  }
});

// ---------------------------------------------------------------------------
// Route 2 — POST /api/meal-plan  (Diet Recommendation Agent)
// ---------------------------------------------------------------------------

app.post('/api/meal-plan', async (req, res) => {
  try {
    const profile  = parseProfile(req.body);
    const response = await dietRecommendationAgent(callGranite, profile);
    res.json({ response });
  } catch (err) {
    handleError(res, err);
  }
});

// ---------------------------------------------------------------------------
// Route 3 — POST /api/recommend  (Diet Recommendation Agent — food list)
// ---------------------------------------------------------------------------

app.post('/api/recommend', async (req, res) => {
  try {
    const profile  = parseProfile(req.body);
    const response = await foodRecommendationAgent(callGranite, profile);
    res.json({ response });
  } catch (err) {
    handleError(res, err);
  }
});

// ---------------------------------------------------------------------------
// Route 4 — POST /api/health-advice  (Health Advisory Agent)
// ---------------------------------------------------------------------------

app.post('/api/health-advice', async (req, res) => {
  try {
    const { topic } = req.body;
    if (!topic || !topic.trim()) {
      return res.status(400).json({ error: 'Topic is required.' });
    }
    const profile  = parseProfile(req.body);
    const response = await healthAdvisoryAgent(callGranite, topic.trim(), profile);
    res.json({ response });
  } catch (err) {
    handleError(res, err);
  }
});

// ---------------------------------------------------------------------------
// Route 5 — POST /api/log-feedback  (Food Log & Feedback Agent)
// ---------------------------------------------------------------------------

app.post('/api/log-feedback', async (req, res) => {
  try {
    const { logEntries } = req.body;
    const profile        = parseProfile(req.body);
    const response       = await foodLogFeedbackAgent(callGranite, logEntries, profile);
    res.json({ response });
  } catch (err) {
    handleError(res, err);
  }
});

// ---------------------------------------------------------------------------
// Route 6 — GET /api/food-lookup?name=  (RAG food lookup — used by frontend)
// ---------------------------------------------------------------------------

app.get('/api/food-lookup', (req, res) => {
  const name = (req.query.name || '').trim();
  if (!name) {
    return res.status(400).json({ error: 'name query parameter is required.' });
  }
  const food = lookupFood(name);
  if (!food) {
    return res.status(404).json({ error: `Food "${name}" not found in dataset.` });
  }
  res.json({ food });
});

// ---------------------------------------------------------------------------
// Start Server
// ---------------------------------------------------------------------------

if (!WATSONX_API_KEY || !PROJECT_ID) {
  console.warn(
    '\n⚠️  WARNING: WATSONX_API_KEY or WATSONX_PROJECT_ID is not set in .env\n' +
    '   The server will start but AI routes will fail until credentials are provided.\n'
  );
}

app.listen(PORT, () => {
  console.log(`\n🥗 NutriGuide AI server running at http://localhost:${PORT}`);
  console.log(`   Model  : ${GRANITE_MODEL}`);
  console.log(`   Region : ${REGION}`);
  console.log(`   Project: ${PROJECT_ID || '(not set)'}\n`);
});
